"""Generate the acados C solver for the Crazyflie linear MPC.

Usage:  python3 mpc_codegen/generate_solver.py
Output: mpc_codegen/c_generated_code/  (acados solver + cf_mpc_constants.h)

The OCP at every sample is

    min   sum_{k=0}^{N-1} |x_k - x_ref_k|_Q^2 + |u_k - u_ref_k|_R^2
          + |x_N - x_ref_N|_P^2
    s.t.  x_{k+1} = Ad x_k + Bd u_k        (linear hover model, ZOH)
          u_min <= u_k <= u_max
          x_0 = current state estimate

P is the solution of the discrete algebraic Riccati equation (the LQR
cost-to-go), so the MPC equals the LQR whenever no bound is active.
"""
import sys
from pathlib import Path

import numpy as np
import scipy.linalg
import yaml
from acados_template import AcadosModel, AcadosOcp, AcadosOcpSolver
import casadi as ca

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE.parent / "model"))
import cf_model  # noqa: E402

SOLVER_NAME = "cf_mpc"
OUTPUT_DIR = HERE / "c_generated_code"


def load_tuning():
    with open(HERE / "mpc_tuning.yaml") as f:
        return yaml.safe_load(f)


def input_bounds(params, tuning):
    """Return (u_min, u_max) for [phi_cmd, theta_cmd, thrust_delta]."""
    hover = params["mass"] * params["gravity"]
    thrust_min = tuning["min_thrust_ratio"] * hover
    thrust_max = tuning["max_thrust_ratio"] * cf_model.max_total_thrust(params)
    tilt = tuning["max_tilt"]
    u_min = np.array([-tilt, -tilt, thrust_min - hover])
    u_max = np.array([tilt, tilt, thrust_max - hover])
    return u_min, u_max


def terminal_weight(Ad, Bd, Q, R):
    return scipy.linalg.solve_discrete_are(Ad, Bd, Q, R)


def build_ocp(params, tuning):
    dt = tuning["sample_time"]
    N = tuning["horizon_steps"]
    A, B = cf_model.linear_model(params)
    Ad, Bd = cf_model.discretize(A, B, dt)
    Q = np.diag(tuning["state_weights"])
    R = np.diag(tuning["input_weights"])
    P = terminal_weight(Ad, Bd, Q, R)
    u_min, u_max = input_bounds(params, tuning)

    model = AcadosModel()
    model.name = SOLVER_NAME
    x = ca.SX.sym("x", cf_model.NX)
    u = ca.SX.sym("u", cf_model.NU)
    model.x = x
    model.u = u
    model.disc_dyn_expr = ca.DM(Ad) @ x + ca.DM(Bd) @ u

    ocp = AcadosOcp()
    ocp.name = SOLVER_NAME  # fixed name -> stable file and function names
    ocp.model = model
    ocp.solver_options.N_horizon = N
    ocp.solver_options.tf = N * dt

    nx, nu = cf_model.NX, cf_model.NU
    ny = nx + nu
    # Stage cost: y = [x; u], weight blockdiag(Q, R)
    ocp.cost.cost_type = "LINEAR_LS"
    ocp.cost.Vx = np.vstack([np.eye(nx), np.zeros((nu, nx))])
    ocp.cost.Vu = np.vstack([np.zeros((nx, nu)), np.eye(nu)])
    ocp.cost.W = scipy.linalg.block_diag(Q, R)
    ocp.cost.yref = np.zeros(ny)
    # Terminal cost: y_e = x_N, weight P
    ocp.cost.cost_type_e = "LINEAR_LS"
    ocp.cost.Vx_e = np.eye(nx)
    ocp.cost.W_e = P
    ocp.cost.yref_e = np.zeros(nx)

    ocp.constraints.idxbu = np.arange(nu)
    ocp.constraints.lbu = u_min
    ocp.constraints.ubu = u_max
    ocp.constraints.x0 = np.zeros(nx)

    ocp.solver_options.integrator_type = "DISCRETE"
    ocp.solver_options.qp_solver = "PARTIAL_CONDENSING_HPIPM"
    ocp.solver_options.hessian_approx = "GAUSS_NEWTON"
    # The problem is a QP, so one SQP iteration solves it exactly.
    ocp.solver_options.nlp_solver_type = "SQP_RTI"
    # acados multiplies each stage cost by the step length by default.
    # Our cost is already a discrete-time sum, so no scaling.
    ocp.solver_options.cost_scaling = np.ones(N + 1)
    ocp.code_gen_options.code_export_directory = str(OUTPUT_DIR)
    ocp.code_gen_options.json_file = str(OUTPUT_DIR / f"{SOLVER_NAME}_ocp.json")
    return ocp, Ad, Bd, P, u_min, u_max


def write_constants_header(tuning, u_min, u_max):
    """Values the C++ side needs to match the generated solver."""
    lines = [
        "// GENERATED by mpc_codegen/generate_solver.py - do not edit.",
        "#pragma once",
        "",
        "namespace cf_mpc_constants {",
        f"constexpr double kSampleTime = {tuning['sample_time']!r};  // s",
        f"constexpr int kHorizonSteps = {tuning['horizon_steps']};",
        f"constexpr double kMaxTilt = {tuning['max_tilt']!r};  // rad",
        f"constexpr double kThrustDeltaMin = {float(u_min[2])!r};  // N",
        f"constexpr double kThrustDeltaMax = {float(u_max[2])!r};  // N",
        f"constexpr double kYawGain = {tuning['yaw_gain']!r};  // 1/s",
        f"constexpr double kMaxYawRate = {tuning['max_yaw_rate']!r};  // rad/s",
        f"constexpr double kDisturbanceTimeConstant = {tuning['disturbance_time_constant']!r};  // s",
        f"constexpr double kMaxDisturbanceRatio = {tuning['max_disturbance_ratio']!r};",
        f"constexpr double kObserverMinHeight = {tuning['observer_min_height']!r};  // m",
        "}  // namespace cf_mpc_constants",
        "",
    ]
    (OUTPUT_DIR / "cf_mpc_constants.h").write_text("\n".join(lines))


def main():
    params = cf_model.load_params()
    tuning = load_tuning()
    ocp, _, _, _, u_min, u_max = build_ocp(params, tuning)
    # Generates the C code, compiles it into a shared library and loads it.
    AcadosOcpSolver(ocp, verbose=False)
    write_constants_header(tuning, u_min, u_max)
    print("Solver generated in", OUTPUT_DIR)


if __name__ == "__main__":
    main()
