// Position/velocity MPC for the Crazyflie (no ROS in this file).
//
// The MPC solver (generated by mpc_codegen/generate_solver.py) uses a model
// linearised at hover with yaw = 0. To use it at any yaw, positions and
// velocities are rotated into the "yaw frame" (world frame rotated by the
// current yaw). With ZYX Euler angles, roll and pitch are already defined
// in that frame, so they need no rotation and the solver's roll/pitch
// commands go to the drone unchanged.
#pragma once

#include <array>
#include <vector>

#include <Eigen/Dense>

#include "cf_model/params.hpp"

struct cf_mpc_solver_capsule;  // from the generated acados code

namespace cf_mpc {

constexpr int kNx = 8;  // [px, py, pz, vx, vy, vz, phi, theta]
constexpr int kNu = 3;  // [phi_cmd, theta_cmd, thrust_delta]

struct VehicleState {
  Eigen::Vector3d position = Eigen::Vector3d::Zero();  // m, world
  Eigen::Vector3d velocity = Eigen::Vector3d::Zero();  // m/s, world
  double roll = 0.0;   // rad
  double pitch = 0.0;  // rad
  double yaw = 0.0;    // rad
};

// One reference point per horizon stage (horizon_steps + 1 points).
struct Reference {
  std::vector<Eigen::Vector3d> positions;   // m, world
  std::vector<Eigen::Vector3d> velocities;  // m/s, world
  double yaw = 0.0;                         // rad
};

struct AttitudeCommand {
  double roll = 0.0;          // rad
  double pitch = 0.0;         // rad
  double yaw_rate = 0.0;      // rad/s
  double thrust = 0.0;        // N, total
  double thrust_cmd = 0.0;    // 0..65535, per motor (firmware "base thrust")
};

struct MpcOutput {
  AttitudeCommand command;
  bool ok = false;            // false if the QP solver failed
  int solver_status = 0;      // acados status code
  double solve_time = 0.0;    // s
};

// Thin wrapper around the generated acados solver.
class AcadosMpc {
 public:
  AcadosMpc();
  ~AcadosMpc();
  AcadosMpc(const AcadosMpc&) = delete;
  AcadosMpc& operator=(const AcadosMpc&) = delete;

  int horizon_steps() const;
  double sample_time() const;

  // x0: current state. x_ref: horizon_steps + 1 reference states.
  // Writes the first optimal input to u0. Returns the acados status (0 = ok).
  int solve(const Eigen::Matrix<double, kNx, 1>& x0,
            const std::vector<Eigen::Matrix<double, kNx, 1>>& x_ref,
            Eigen::Matrix<double, kNu, 1>& u0, double& solve_time);

 private:
  cf_mpc_solver_capsule* capsule_ = nullptr;
};

class MpcController {
 public:
  explicit MpcController(const cf_model::Params& params);

  int horizon_steps() const { return mpc_.horizon_steps(); }
  double sample_time() const { return mpc_.sample_time(); }

  MpcOutput compute(const VehicleState& state, const Reference& reference);

 private:
  cf_model::Params params_;
  AcadosMpc mpc_;
};

// Reference that holds one position for the whole horizon.
Reference make_hold_reference(const Eigen::Vector3d& position, double yaw,
                              int horizon_steps);

// Angle wrapped to (-pi, pi].
double wrap_angle(double angle);

// Rotates a world-frame vector into the yaw frame (rotation by -yaw about z).
Eigen::Vector3d world_to_yaw_frame(const Eigen::Vector3d& v, double yaw);

}  // namespace cf_mpc
